export const MAKE_REQUEST_START='MAKE_REQUEST_START';
export const MAKE_REQUEST_SUCCESS='MAKE_REQUEST_SUCCESS';
export const MAKE_REQUEST_FAIL='MAKE_REQUEST_FAIL';

export const SELECT_ITEM='SELECT_ITEM';

export const CHECK_CACHE='CHECK_CACHE';




